### ISSUE TITLE
Project not appearing correctly in the showcase page

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103T-F13-4/main#121]
https://nus-cs2103-ay1920s1.github.io/website/admin/projectList.html#cs2103t-f13-4

![image](https://user-images.githubusercontent.com/1673303/67618577-d30e8a00-f823-11e9-88d0-a9b25717c6d8.png)

**Comment by heze8** [comment]
Hello, should be resolved already. Thanks for notifying us!
